"""initial schema

Revision ID: 387972c0cac7
Revises: 
Create Date: 2026-09-21 22:59:01.397407

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '387972c0cac7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento'))
    )
    op.create_table('sexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sexo'))
    )
    op.create_table('tokenblacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokenblacklist'))
    )
    with op.batch_alter_table('tokenblacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokenblacklist_jti'), ['jti'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_failed_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_area_evento_id_evento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_area'))
    )
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('escuela', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usada', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_entrada_evento_id_evento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entrada')),
    sa.UniqueConstraint('uuid', name=op.f('uq_entrada_uuid'))
    )
    op.create_table('modalidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_modalidad_evento_id_evento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modalidad'))
    )
    op.create_table('passwordresettoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_passwordresettoken_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passwordresettoken'))
    )
    with op.batch_alter_table('passwordresettoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passwordresettoken_token'), ['token'], unique=True)

    op.create_table('competidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('escuela', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('modalidad_id', sa.Integer(), nullable=True),
    sa.Column('sexo_id', sa.Integer(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('historial', sa.Integer(), nullable=False),
    sa.Column('historial_str', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comentarios', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_competidor_evento_id_evento')),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], name=op.f('fk_competidor_modalidad_id_modalidad')),
    sa.ForeignKeyConstraint(['sexo_id'], ['sexo.id'], name=op.f('fk_competidor_sexo_id_sexo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competidor'))
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competidor_1_id', sa.Integer(), nullable=False),
    sa.Column('competidor_2_id', sa.Integer(), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('comentarios', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], name=op.f('fk_match_area_id_area')),
    sa.ForeignKeyConstraint(['competidor_1_id'], ['competidor.id'], name=op.f('fk_match_competidor_1_id_competidor')),
    sa.ForeignKeyConstraint(['competidor_2_id'], ['competidor.id'], name=op.f('fk_match_competidor_2_id_competidor')),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_match_evento_id_evento')),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad.id'], name=op.f('fk_match_modalidad_id_modalidad')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('competidor')
    with op.batch_alter_table('passwordresettoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passwordresettoken_token'))

    op.drop_table('passwordresettoken')
    op.drop_table('modalidad')
    op.drop_table('entrada')
    op.drop_table('area')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('tokenblacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokenblacklist_jti'))

    op.drop_table('tokenblacklist')
    op.drop_table('sexo')
    op.drop_table('evento')
    # ### end Alembic commands ###
